- pom.xml
Bump lombok version to 1.18.22
I was experiencing the following error in IntelliJ
```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
Your processor is: com.sun.proxy.$Proxy32
Lombok supports: OpenJDK javac, ECJ
```
This is related to https://youtrack.jetbrains.com/issue/IDEA-252069, and is fixed in recent lombok versions.
```
mvn clean verify
```
> chore: bump lombok to 1.18.22

- src/main/java/com/aws/greengrass/mqttbridge/MQTTBridge.java
Currently we subscribe to `mqttTopicMapping` that can be removed with a reset `[""]`. 
Preserve the subscription with subscribing to `configuration`
When we reset the configuration for `mqttTopicMapping` using [""], we lose the subscription in the process.
Any further updates to the config are not parsed by Bridge.
`mvn clean verify`
> fix: config reset bug

- src/main/java/com/aws/greengrass/mqttbridge/auth/MQTTClientKeyStore.java
- src/main/java/com/aws/greengrass/mqttbridge/clients/MQTTClient.java
- src/test/java/com/aws/greengrass/mqttbridge/auth/MQTTClientKeyStoreTest.java
- src/test/java/com/aws/greengrass/mqttbridge/clients/MQTTClientTest.java
It is not necessary to disconnect the MQTT Bridge when the client
certificate rotates. This change removes that logic, but still ensures
that the new client certificate is used the next time the bridge
connects.
CA rotation still results in a disconnect, as that indicates that the
client should no longer trust the server.
> fix: remove client certificate rotate callback

- src/main/java/com/aws/greengrass/mqttbridge/MessageBridge.java
- src/main/java/com/aws/greengrass/mqttbridge/TopicMapping.java
- src/test/java/com/aws/greengrass/mqttbridge/MQTTBridgeTest.java
- src/test/java/com/aws/greengrass/mqttbridge/MessageBridgeTest.java
- src/test/resources/com/aws/greengrass/mqttbridge/config_with_mapping.yaml
GH-68
Added a new configuration option named `targetTopicPrefix`. This configuration option will add a prefix to the target topic before sending the message to the target integration.
This allows for managing IPC topics separate from MQTT topics.
`mvn clean verify`
> Added `targetTopicPrefix`

- pom.xml
- recipe.json
- src/main/java/com/aws/greengrass/mqttbridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqttbridge/auth/MQTTClientKeyStore.java
- src/test/java/com/aws/greengrass/mqttbridge/MQTTBridgeTest.java
- src/test/java/com/aws/greengrass/mqttbridge/auth/MQTTClientKeyStoreTest.java
Removes CSR generation logic for getting client certificates and instead uses the subscribeToCertificateUpdates API
Depends on https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/95
CI will fail until the above is merged.
> chore: migrate to subscribeToCertificateUpdates API

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClient.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClientTest.java
* Adjust the behavior of `IotCoreClient` so that subscriptions are retried in the event greengrass was started offline.
* Return early if interrupted in `IotCoreClient#subscribeToTopicsWithRetry`
Customers may start greengrass while offline so we must handle that scenario in `IotCoreClient`
Unit test and UAT
> fix: retry IotCoreClient subscriptions when greengrass starts offline

- src/main/java/com/aws/greengrass/mqtt/bridge/MessageBridge.java
Change the log level in the message bridge for each received and sent message down to debug. It was logging at info for every single message which is forwarded which can have an enormous volume.
> fix(logging): drop message sent/received to debug level

- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MessageClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/PubSubClient.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
Adds a `LocalMqttClientFactory`, to allow bridge to choose between mqtt3 and 5 clients, based on configuration.
To support v3 and v5 local mqtt clients
unit tests
> feat: local mqtt client factory

- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
Fixes bug where CDA CA subscriptions accumulate for every call to `install`.  Additionally, CDA subscription code has been consolidated to a class, `CertificateAuthorityChangeHandler`, and has been refactored to use `BatchedSubscriber`.
To prevent duplicate subscriptions to CDA topics
unit tests
> fix: unsubscribe to CDA CA conf

- pom.xml
- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/config.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/config_with_mapping.yaml
Adds integration test config to pom.xml and adds empty int test classes.  Follow-up PRs will move over int tests from `MQTTBridgeTest` to here.
Cleaner separation of int tests (currently mixed in unit tests), and to be consistent with other components
> feat: integration test skeleton

- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
UATs are failing because bridge is reading CDA CA topic incorrectly, reverting back to previous approach of topic.toPOJO
> fix: toPojo when reading cda topic

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/TopicMapping.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
Move integration tests from `MQTTBridgeTest` to `KeystoreTest` and `ConfigTest` integration test classes
> refactor: move int tests to integrationtests folder

- pom.xml
Bump nucleus to 2.10.0-SNAPSHOT to get mqtt5 models
> chore: upgrade nucleus for mqtt5

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
Refactor `ConfigTest` and `KeystoreTest` so that they use `@BridgeIntegrationTest` (introduced in https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/96).  Functionally, everything is the same, just a lot of boilerplate cleanup
> refactor: use BridgeIntegrationTest for existing integration tests

- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
address flaky test failure seen in https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/98 
> chore: bump timeout in KeystoreTest

- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
Adds the following global mqtt5 configuration options:
```
brokerClient.noLocal = false
brokerClient.receiveMaximum = 65535  (range 1 to 65535)
brokerClient.maximumPacketSize = null (range 1 to 4294967295)
brokerClient.sessionExpiryInterval = 4294967295 (range 0 to 4294967295)
```
⚠️ If configured numerical values are out of range, they will be clamped to the min/max value.  e.g. 4294967296 becomes 4294967295
Per-route config will be added in a subsequent PR
> feat: global mqtt5 config

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/config_with_mapping.yaml
- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/model/Mqtt5RouteOptions.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
Adds mqtt5-specific route options via a new `mqtt5RouteOptions` config.  This config is a mapping from route name to properties, similar to the existing `mqttTopicMapping` config option.
```
"mqtt5RouteOptions": {
"route1": {
"noLocal": false,
"retainAsPublished": true
},
"route2": {
...
},
...
}
```
Also configures objectmapper to allow unrecognized properties, so mqtt5 route config can grow over time.
⚠️ As discovered through this PR, we must not add fields to `mqttTopicMappings` as this will break backwards compatibility, due to objectmapper for current/previous bridge versions not being configured to allow unrecognized values.
**Any additional information or context …
> feat: per-route mqtt5 config

- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
Removing the global `noLocal` config since we are using per-route `noLocal` instead.
> chore: remove global noLocal config, in favor of per-route

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/model/MqttMessage.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClientTest.java
Use v5 spooler models in `IotCoreClient`.  Async operations not yet supported, will be in a follow-up in https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/103.
> feat: support mqtt5 in iot core client

- src/test/java/com/aws/greengrass/mqtt/bridge/clients/FakePahoMqtt3Client.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/FakePahoMqtt3ClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MockMqttClient.java
* New `MockMqttClient`, which tries to be a fake, although it accomplishes it using mocks since MqttClient doesn't have an interface
* Rename `FakeMqttClient[Test]` to `FakePahoMqtt3Client[Test]` for clarity, since we now have CRT and mqtt5 in the mix.
* Utilize `MockMqttClient` in `IotCoreClientTest`
* allows `IotCoreClientTest` to work regardless if `IotCoreClient` impl is sync or async
* `MockMqttClient` can be used in integration tests
> refactor: add MockMqttClient, cleanup IotCoreClientTest

- src/integrationtests/java/com/aws/greengrass/integrationtests/BridgeTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestContext.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt3_local_and_iotcore.yaml
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/IoTCoreClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
Adds a new integration test, `BridgeTest` for exercising message bridging between message clients.  For now a few tests for bridging IotCore <--> Local (v3) were added, making use of the mock mqttclient from https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/105.
Also improves integration test extension so that it waits for local mqtt client to fully connect before executing the test. 
> chore: utilize IotCoreClient in integration tests

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestContext.java
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/main/java/com/aws/greengrass/mqtt/bridge/model/BridgeConfigReference.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
Wrap `BridgeConfig` in an atomic reference and inject that wherever config is needed, for convenience.  `MQTTBridge` is responsible for updating the reference
Refactoring now in preparation for using route config within other parts of bridge.  It's easier to use bridge config if we can inject it, rather than using setters and making sure those are all properly called. (e.g. `localMqttClientFactory.setConfig(bridgeConfig);`)
> refactor: injectable bridge config

- src/main/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStore.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClientTest.java
Spotted in integration testing, when we switch between local mqtt clients, the old one still gets their `reset` triggered on keystore updates, so we need an unsubscribe mechanism.
> fix: unsubscribe from keystore updates

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
Fix a null pointer when `MQTTClient#reset` is invoked before `MQTTClient` constructor completes
As seen in https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/113 test runs:
```
2023-03-29T23:12:31.7379239Z 2023-03-29T23:12:29.496Z [ERROR] (Serialized listener processor) com.aws.greengrass.dependency.Context: run-on-publish-queue-error. {}
2023-03-29T23:12:31.7379638Z java.lang.NullPointerException
2023-03-29T23:12:31.7379989Z 	at com.aws.greengrass.mqtt.bridge.clients.MQTTClient.reset(MQTTClient.java:124)
2023-03-29T23:12:31.7380464Z 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
2023-03-29T23:12:31.7380944Z 	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.jav …
```
> fix: null pointer in MQTTClient reset

- src/main/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStore.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
Was seeing tls negotiation failed errors in UAT.  Some research led to https://github.com/aws/aws-iot-device-sdk-java-v2/commit/a27d4c8deb86b6c9fbb036aff3095da8b4391ca6, so was able to get UAT to pass when configuring this option.
UAT
> fix: add ca cert to mqtt5client

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
Our mqtt5 client currently doesn't work with ssl for windows/mac, due to https://github.com/awslabs/aws-c-io/issues/260. To workaround in the meantime, bridge can encode keys with pkcs1
Unblock local and windows integration and uat
> chore: workaround using pkcs1

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/RetryableMqttOperationException.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
Adding handling for SubAck reason codes. If the reason codes indicate a success or a non-retryable error (such as not being authorized), then the subscription will not be retried. Otherwise the subscription will be retried according to the set RetryUtils configuration. 
Previously, no subscriptions errors were being retried on. This change will retry on errors that have the possibility of succeeding on consecutive runs.
Unit tests
> feat: handle retries on suback reason codes

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/config.yaml
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
* FIx race condition in `GIVEN_mqtt_bridge_WHEN_cda_ca_conf_changed_after_shutdown_THEN_bridge_keystore_not_updated`.  Fully wait for bridge to break before listening to keystore updates.
* Add test coverage where cda ca topic value is invalid
* Improve topic handling code so that we explicitly ignore bad cases using `Optional.empty()` rather than filtering on empty list, which may filter out case where ca is removed (not that that would ever happen in practice, more about correctness)
* add debug logging for tests that use `config.yaml`.
* fix test failures for tests that debug logged (expected) connection failures 
**Any additional information or context required to …
> fix: flaky keystore integration test

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
Adding handling for UnSubAck reason codes. If the reason codes indicate a success or a non-retryable error, then it will not attempt to unsubscribe from the topic again. Otherwise the it will be retried according to the set RetryUtils configuration. 
Previously, no unsubscribe errors were being retried on. This change will retry on errors that have the possibility of succeeding on consecutive runs.
Unit tests
> feat: handle retries on unsuback reason codes

- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
Adds the following configuration properties:
* ackTimeoutSeconds
* connAckTimeoutMs
* pingTimeoutMs
* maxReconnectDelayMs
* minReconnectDelayMs
Customers can customize how long the local mqtt5 client waits for various operations
> chore: make client timeouts configurable

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
Bridge MQTT3 client currently only allows 10 "inflight" QOS1 messages, which limits performance.  This change removes paho's inflight limit by setting it to max possible value.
> chore: remove paho max inflight limit

- pom.xml
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/test/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStoreTest.java
Upgrade junit to latest, mockito to latest minor/patch, and lombok to latest
Not strictly necessary because we build with java 8, but was useful when I wanted to run profiling in IntelliJ, which required me to use a JDK > 1.8.
Ran unit and integ tests with jdk 8 and jdk 18
> chore: upgrade junit, mockito, and lombok

- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
Adds `brokerClient/keepAliveTimeoutSeconds` configuration property, and ensures keep alive is greater than or equal to ping timeout.
Unit tests
> feat: configurable keep alive

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_config_ssl.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_connect_options.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_and_iotcore.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_to_iotcore_nolocal.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_to_iotcore_retain_as_published.yaml
- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
For consistency with spooler mqtt client, rename bridge's `brokerClient` configuration to `mqtt`.
unit and integration tests
> chore: rename brokerClient config to mqtt

- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/test/java/com/aws/greengrass/mqtt/bridge/BridgeConfigTest.java
Lower the default receive maximum to `100`, matching spooler
Consistency with spooler, and using a more sane default value than 65535
> chore: adjust default receive maximum

- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestContext.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/Certs.java
- src/main/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStore.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
- src/test/java/com/aws/greengrass/mqtt/bridge/MQTTBridgeTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStoreTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MockMqtt5Client.java
Reset `LocalMqtt5Client` after CDA generates a client certificates so that it may used in the MQTT connection.
Client certificates rotate weekly by default and bridge mqtt5 client needs a way to use the new certificates.
* rotate client cert and verify that local client resets
* rotate ca cert, server cert, and client cert, and verify local client resets
* rotate client certs in rapid succession, to test concurrency
* verify that resets will be retried on failure
Rotated client certs in a loop for 40 minutes, memory looks pretty stable
Both integration tests use certificates that are used by both broker (HiveMQ) and client.  the broker will dynamically reload on server …
> fix(mqtt5) react to client certificate rotations

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
Refactor mqtt5 client so that it always subscribes to keystore updates on start and then filters events.
Eventually mqtt5 client will reset on configuration changes.  With this change, we don't need to worry about subscribing/unsubscribing to keystore when brokerUri changes, which opens the possibility of missing events.
> refactor: always subscribe to keystore updates

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
Move local mqtt5 client configuration fields to a builder class
> refactor: client config as builder

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MockMqtt5Client.java
Fix mqtt5 client such that when we reconnect without a session, topics are resubscribed. Currently no topics will resubscribe.
> fix: clear topics if disconnected without a session

- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
We see that bridge can timeout when shutting down due to the MQTT 3 client taking time to disconnect. We do not know if this is due to the quiescence of 30s default or not, but this change just sets it to 0 time to quiesce. Also increasing the shutdown timeout from 15s to 120s.
> fix: 0 quiescence time for mqtt 3 disconnect and 120s shutdown timeout

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MessageClient.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClientTest.java
Adding a call to `IMqttClient#close` when shutting down to ensure paho client is fully closed.  Because we close the client, client creation has been moved to `start()` instead of in the constructor.
Due to previous change where reconnect in paho callback is async, it was discovered that this reconnect will happen even after stopping MQTTClient.
> fix: close mqtt3 client on stop

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
1) Always attempt to disconnect, so paho can close the client (paho won't close if connect is in progress).  
2) Explicitly bail from connect loop if paho client is closed.
3) also fixes a bug where subscription state isn't cleared before a `reset()`
> fix: ensure connect loop stops on client close

- src/integrationtests/java/com/aws/greengrass/integrationtests/ConfigTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/main/java/com/aws/greengrass/mqtt/bridge/BridgeConfig.java
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqttClientFactory.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5ClientTest.java
- src/test/java/com/aws/greengrass/mqtt/bridge/clients/MockMqtt5Client.java
Reset local mqtt5 client on config changes rather than reinstall bridge.
Improves customer experience by only interrupting local client rather than unnecessarily interrupting the entire bridge.
New unit tests
> feat: reset mqtt5 client on config change

- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
force disconnect on shutdown
* fixes issue where disconnect attempt fails due to client being connected (race condition between cancelling MQTTClient's async connect task and calling disconnect)
With integration test from https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/163 that triggers the condition from 1)
> fix: improve MQTTClient shutdown reliability

- src/integrationtests/java/com/aws/greengrass/integrationtests/LifecycleTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/reinstalling_bridge.yaml
- src/main/java/com/aws/greengrass/mqtt/bridge/MQTTBridge.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/MQTTClient.java
Synchronize lifecycle methods in MQTTBridge
There's a chance that multiple MQTTClients can be active at the same time if startup and shutdown methods overlap, which is possible if reinstall is requested during startup.  When this occurs, the two MQTTClients step on each other, causing a connect/disconnect loop between them.  This behavior has been seen recently in customer logs.
New integration test, plus changes from https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/162.  Verified that the new test fails without the fixes and passes with the fixes
By submitting this pull request, I …
> fix: synchronize lifecycle methods

- src/main/java/com/aws/greengrass/mqtt/bridge/auth/MQTTClientKeyStore.java
- src/main/java/com/aws/greengrass/mqtt/bridge/clients/LocalMqtt5Client.java
Move cert/key getting functionality into `MQTTClientKeystore`
These methods can be reused when replacing the mqtt3 client with aws iot client
> refactor: add cert and key getters to keystore

- pom.xml
- src/integrationtests/java/com/aws/greengrass/integrationtests/KeystoreTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/LifecycleTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestContext.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/BridgeIntegrationTestExtension.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/extensions/Certs.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/config_with_mapping.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/extensions/config.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt3_config_ssl.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt3_local_and_iotcore.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_connect_options.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_and_iotcore.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_to_iotcore_nolocal.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/mqtt5_local_to_iotcore_retain_as_published.yaml
Configure SSL for Moquette within bridge's integration test extension.  This allows us to test SSL communication between bridge's local MQTT3 client and Moquette.
The Moquette version used for integ tests has also been bumped from 0.15 to 0.17, to match the latest version used in the public Greengrass Moquette component.
* New integ test that uses SSL between moquette and bridge mqtt3 client
> feat: ssl for mqtt3 integ tests

- recipe.json
Closes #168.
Update GDK recipe to match real version in AWS.
> chore: bump GDK recipe dependency on CDA version
